version: '3.8'

services:
  workshopservice:
    container_name: horny-workshop.workshop-service
    image: ${DOCKER_REGISTRY-}workshopservice
    build:
      context: .
      dockerfile: Services/WorkshopService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://*:5000;http://*:5001"
    ports:
      - 5000:5000
      - 80:80
    depends_on:
      db:
        condition: service_healthy
    links:
      - db

  db:
    container_name: horny-workshop.postgres
    image: postgres
    # restart: always
    environment:
      - POSTGRES_DB=horny
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_USER} -U $${POSTGRES_USER}"]
      timeout: 1s
      retries: 7
    # ports:
      # - 5002:5432

  admin:
    container_name: horny-workshop.pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@horny.workshop
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    depends_on:
      db:
        condition: service_healthy
    links:
      - db